export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESSED = 'SIGN_IN_SUCCESSED';

export const LOGOUT_PROFILE = 'LOGOUT_PROFILE';

export const EDIT_PROFILE_REQUEST = 'EDIT_PROFILE_REQUEST';
export const EDIT_PROFILE_SUCCESSED = 'EDIT_PROFILE_SUCCESSED';

export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESEED = 'GET_PROFILE_SUCCESSED';

export const GET_USER_PROFILE_REQUEST = 'GET_USER_PROFILE_REQUEST';
export const GET_USER_PROFILE_SUCCESSED = 'GET_USER_PROFILE_SUCCESSED';
