export const GET_MANY_POSTS_REQUEST = 'GET_MANY_POSTS_REQUEST';
export const GET_MANY_POSTS_SUCCESSED = 'GET_MANY_POSTS_SUCCESSED';

export const ADD_POST_REQUEST = 'ADD_POST_REQUEST';
export const ADD_POST_SUCCESSED = 'ADD_POST_SUCCESSED';

export const EDIT_POST_REQUEST = 'EDIT_POST_REQUEST';
export const EDIT_POST_SUCCESSED = 'EDIT_POST_SUCCESSED';
